### PR TITLE
[RFR] Move column_exists so it can be used during loading

### PR DESCRIPTION
**Pull request by StefanRijnhart**
Needed for https://github.com/OCA/OpenUpgrade/pull/640

### CODE REVIEW

**Comment by legalsylvain** [comment]
Thanks. :+1: 
Merging this trivial PR.

**Comment by pedrobaeza** [comment]
I'm afraid it's not so trivial, because there are a lot of scripts that use this method, so now they need to change the import. Please add an alias inside openupgrade.py for not losing compatibility.

**Comment by legalsylvain** [comment]
@pedrobaeza  There is an alias in this PR.
https://github.com/OCA/openupgradelib/pull/57/files#diff-3d7675eb1386de028dab1f879bdc4681R244

**Comment by pedrobaeza** [comment]
Sorry, I didn't see it. Then it's good.

**Pull request merged**
