### PR TITLE
Fix conversion to attachment on large datasets

### PR DESCRIPTION
**Pull request by dreispt**
Selecting all binary data at once will exceed memory limits, and get the
Odoo process killed.
Fetching one by one is not enough, since executing the SELECT to
retrieve all the table data can also fail with a Postgresql "out of
memory" error.

I had a bottleneck on res_partner.image, with almost 5k images to convert.
With this change this upgrade step was successful, and took around 6 minutes to run.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
I'm not sure about the performance of this. Instead of selecting one by one, I think you can read content by chunks of for example 500, which a balance between memory consumption and speed making a lot of independent querys

**Comment by dreispt** [comment]
I had the same thought when writing the code, but when running it the performance penalty didn't seem relevant enough to be worth that complication: smaller tables still took few seconds to process, and the large table processed 5k  images in 6 minutes - doesn't seem unreasonable.

**Comment by gdgellatly** [comment]
Just as a mental exercise I thought of an alternative algorithm to avoid the duplicate selects.  Pseudocode, probably missing something.

```
SELECT id's FROM table WHERE field not=NULL
for id in ids:
    ir_attachment.create('datas': '1')
UPDATE ir_attachment SET datas=field.name FROM model WHERE model.id=res_id AND res_model = model_name AND res_field = field
```
Then the binary data never even hits openupgrade.

**Comment by dreispt** [comment]
I wrote an improvement, following Pedro's suggestion, but I haven't tested it yet: https://github.com/dreispt/openupgradelib/commit/cf38433b06437c3ff1b05f9114953d2ca74cc8e4

**Comment by dreispt** [comment]
PR updated with the new code.
It now works on batches of 500 records.

**Comment by pedrobaeza** [comment]
> It would still be much quicker to create the attachments using SQL in a single query

Not really, check https://stackoverflow.com/questions/8635818/multiple-insert-statements-vs-single-insert-with-multiple-values

**Comment by dreispt** [comment]
🎉 My first OpenUpgrade related contrib!

**Comment by StefanRijnhart** [comment]
@pedrobaeza It's more that you would use SQL instead of the ORM.

**Comment by StefanRijnhart** [comment]
@dreispt thanks and congrats! Keep em coming!

**Comment by pedrobaeza** [comment]
@StefanRijnhart right, I see now the `create` statement

**Pull request merged**
