### PR TITLE
[ADD] delete_constraint_safely: method to delete constraints

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
To be used on v14 onward.

### CODE REVIEW

**Review by pedrobaeza — COMMENTED** [review]
Several comments:

- Isn't the same for previous versions?
- Can we deduce the constraint name from the field instead of having to put the exact name?

**Comment by MiquelRForgeFlow** [comment]
> - Isn't the same for previous versions?

In v13 and previous versions, the constrains don't have an xmlid. So, to make the method compatible with previous versions, I could do:

```python
if version_info[0] > 13:
    delete_records_safely_by_xml_id(
        env, [module + ".constraint_" + table + "_" + name]
    )
```

but, is it worth? Previous versions are already done so I think this method won't be used in them.

> - Can we deduce the constraint name from the field instead of having to put the exact name?

No, the 'name' in the ir.model.constraint model is equivalent with what in this method is `table + "_" + name`. So a 'table' and a 'name' will be introduced as variables one way or the other. My way is a sum and your way would have to do a left trim. Thus, if I have the choice, I prefer the sum. Moreover, my "name" way is straightforward as is the same as it's declared:
Selection_493

**Comment by pedrobaeza** [comment]
Ok, please document the arguments in the docstring with these details for future references.

**Comment by MiquelRForgeFlow** [comment]
Ready

**Pull request merged**
