### PR TITLE
[IMP] copy_columns: Only copy not null values

### PR DESCRIPTION
**Pull request by etobella**
@pedrobaeza @MiquelRForgeFlow @hbrunn @legalsylvain

### CODE REVIEW

**Review by StefanRijnhart — COMMENTED** [review]
Makes sense. Is this just a performance improvement or does it solve errors?
I think I would prefer the commit to include a little more detail. Maybe `[IMP] copy_columns: Only copy not null values`?

**Comment by etobella** [comment]
It should increase the speed. The code itself is right.

**Review by StefanRijnhart — APPROVED** [review]
Thanks!

**Review by MiquelRForgeFlow — APPROVED** [review]
LGTM

**Review by pedrobaeza — APPROVED** [review]

**Pull request merged**
