### PR TITLE
[FIX] use correct column name

### PR DESCRIPTION
**Pull request by hbrunn**
...

### CODE REVIEW

**Comment by pedrobaeza** [comment]
:+1:

**Comment by sebalix** [comment]
:+1:

**Comment by StefanRijnhart** [comment]
Thanks! Sorry for my bad review ;-)

**Comment by pedrobaeza** [comment]
Blame for me too that I didn't see it...

**Comment by hbrunn** [comment]
this of course has nothing to do with a mistake on my side. i just put it there to test you guys

**Comment by pedrobaeza** [comment]
:wink:

**Pull request merged**
