### PR TITLE
[FIX] docstring

### PR DESCRIPTION
**Pull request by hbrunn**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Should we wait to https://github.com/OCA/openupgradelib/issues/82 for changing the documentation at once?

**Comment by hbrunn** [comment]
sounds good, i'm still fighting to get this right anyways

**Comment by hbrunn** [comment]
now it will be green and nice

**Comment by pedrobaeza** [comment]
Well, thinking twice, I'm going to merge this for greenifying things. We can change it later.

**Pull request merged**
