### PR TITLE
[FIX] rename_models method

### PR DESCRIPTION
**Pull request by mreficent**
This PR does:

- [x] Fix `rename_models` method

### CODE REVIEW

**Comment by StefanRijnhart** [comment]
Curious what your use case is for forcefully deleting models?

**Comment by pedrobaeza** [comment]
Yeah, me too. @mreficent you tend to mix things together in the same PR. Please make one per "task", so that we are not forced to process them together. Right now, we could merge already the patch for the model renaming if it was alone.

**Comment by mreficent** [comment]
@pedrobaeza Well, I put them together in the same PR because the two methods are related. Don't tell me they are not. The queries in both methods are similar. In one, they are renaming the model but in the other are deleting it. But by comparing the two, it's easier to understand if the new method consider all the cases or not.

@StefanRijnhart I am retaking the migration of the `mrp/mrp_operations` and by doing some local examples, I realized I need this.

**Comment by StefanRijnhart** [comment]
OK, thanks for the clarification.

**Comment by pedrobaeza** [comment]
It's not the same to be related than to be similar. As they are not related, they shouldn't be in the same PR. I see the delete operation very dangerous. We have been always conservative in data in OpenUpgrade. I prefer a rename operation than a removal.

**Comment by StefanRijnhart** [comment]
Yes, maybe it is better if you file this feature separately when we can review your use case in the mrp migration at the same time.

**Comment by mreficent** [comment]
I want to rename model A to B, but if B already exists the renaming queries give errors because unique contrains. So before renaming A to B, I need to delete B. And it doesn't make sense to rename model B to C.

**Comment by pedrobaeza** [comment]
Yes, because you are destroying information that can be important if you want to recreate another thing. But as said:

- Please leave this PR with only the fix, and we merge.
- Create a new one, and point us to the use case in MRP, so that we can analyze it.

**Comment by mreficent** [comment]
Done.

**Comment by mreficent** [comment]
Can be merged :)

**Comment by StefanRijnhart** [comment]
Thanks ;-)

**Pull request merged**
