### PR TITLE
[FIX] merge_records: missing argument in _adjust_merged_values_orm

### PR DESCRIPTION
**Pull request by mreficent**
Bug.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Well, then it's advisable to add the logic for excluding that columns indeed.

**Comment by mreficent** [comment]
What do you mean? The exclusion of columns was for other methods, not for this one. This method doesn't have to exclude anything. Just happens that all methods are called with the same arguments and so this one has to have that argument.

**Comment by pedrobaeza** [comment]
I would say that you haven't to adjust values for the excluded columns.

**Comment by StefanRijnhart** [comment]
Thanks for the fix! If it's not used, maybe don't pass it at all but change the composition of args2 not to include it.

**Comment by mreficent** [comment]
Done. I think now it's ok for all tastes :)

**Comment by pedrobaeza** [comment]
I'm afraid this is still not correct: https://travis-ci.org/OCA/OpenUpgrade/builds/442749754#L6799

**Pull request merged**
