### PR TITLE
[FIX] rename_models

### PR DESCRIPTION
**Pull request by mreficent**
In v11, the `model_name` field of `ir_act_server` became stored.

### CODE REVIEW

**Comment by mreficent** [comment]
But in the pre-migration of `base` in v11, the column `model_name` will not be created yet, right? 🤔

**Comment by astirpe** [comment]
Thanks!
Same issue affects `mail.template`: the field `model` (Varchar) is not updated with the value of `model_id.name`.

I guess there will be other similar cases in other modules.

**Comment by mreficent** [comment]
Well, I will not check for other cases. If you want to check, then check it, and I will update accordingly 😉

**Comment by pedrobaeza** [comment]
This shouldn't take into account general data model, not specific modules models. `mail` can be an exception as it's a very base module, but you should always check any way if the model/table/column exists. You can't assume it exists.

The rest of the changes should be done on specific migration scripts for that module.

**Comment by mreficent** [comment]
Just used table_exists and column_exists everywhere XD

**Comment by mreficent** [comment]
he he he but you could have done that before  🙄

**Comment by pedrobaeza** [comment]
Well, we are touching now this, so it's when it raises.

**Comment by mreficent** [comment]
Ok. But should I put the `logged_query` in all of them or just in some specific ones? I think that putting on all of them is too much log.

**Comment by pedrobaeza** [comment]
As said about the rule: in all of them that makes a massive change. Don't worry about being too much: log is something optional that you can even disable, and in this case the verbosity is thankful knowing the number of records modified for tracking possible problems.

**Comment by mreficent** [comment]
done, logged all :)

**Pull request merged**
