### PR TITLE
[IMP] BS4->BS5: performance

### PR DESCRIPTION
**Pull request by chienandalu**
Avoid record values which html is empty using the same rules that odoo.tools.is_html_empty uses. This way we can simplify the call avoiding a default domain as well. In any case, we can use that domain to refine certain models.

cc @Tecnativa TT46020

please check @pedrobaeza

### CODE REVIEW

**Review by legalsylvain — APPROVED** [review]
nice improvment.

**Review by pedrobaeza — APPROVED** [review]

**Comment by hhgabelgaard** [comment]
@chienandalu @pedrobaeza What's the Python version compability requirements for OpenUpgradelib?
2.7 according to  setup.py https://github.com/OCA/openupgradelib/blob/master/setup.py#L53

So please avoid f-strings - Some of us are using OpenUpgrade on older Odoo/Python versions

**Comment by pedrobaeza** [comment]
We are using them too in old versions, but look that this is something exclusively for version 16.0. Where are the problem?

**Comment by StefanRijnhart** [comment]
@pedrobaeza this is the problem
```
>>> import openupgradelib
>>> from openupgradelib import openupgrade_tools
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "openupgradelib/openupgrade_tools.py", line 415
    )"""
       ^
SyntaxError: invalid syntax
```

**Comment by StefanRijnhart** [comment]
Maybe we should bump the version with a major and drop compatibility with Python 2.x.

**Comment by pedrobaeza** [comment]
OK, I think we can remove the f-string, as it's not strictly needed. @chienandalu can you?

**Comment by chienandalu** [comment]
No problem

**Comment by chienandalu** [comment]
Addressing fixes here: https://github.com/OCA/openupgradelib/pull/371

**Comment by hhgabelgaard** [comment]
@chienandalu Thanks!

This community rocks!

**Pull request merged**
