### PR TITLE
[IMP][merge_records] Improve ORM performance by using IN instead of ORs

### PR DESCRIPTION
**Pull request by ivantodorovich**
Fixes https://github.com/OCA/OpenUpgrade/issues/1445

### CODE REVIEW

**Comment by ivantodorovich** [comment]
ping @legalsylvain @pedrobaeza

**Comment by pedrobaeza** [comment]
Yeah, I designed it that way, but honestly looking now I don't know why not doing with `in`

**Comment by legalsylvain** [comment]
Thanks @pedrobaeza for your quick review.

**Comment by ivantodorovich** [comment]
Thanks!! :)

**Comment by ivantodorovich** [comment]
Yep, got that too :sweat_smile: 
I think there's still room for improvement here, though.

I was thinking instead of looping through the moves one by one, and running 2 queries per each, we could try something like this:
(haven't tested it so code may not work, but you'll get the idea :laughing: )

```py
def update_stock_move_value_fifo(env):
    """New fields 'value', 'remaining_qty' and 'remaining_value' in
    stock.move need to be properly filled for environments using
    perpetual/automated inventory valuation and to not lose the possibility
    to switch to it after migration in envs with manual valuation.
    # Valuate incoming moves:
    # q1: Update remaining value and remaining qty based on quants that
    # still exist in internal locations.
    # q2: Update value based on quants that a linked to this move.
    env.cr.execute("""
        UPDATE stock_move AS to_update
        SET
            remaining_value = q1.remaining_value,
            remaining_qty = q1.remaining_qty,
            value = q2.value
        FROM stock_move AS sm
        INNER JOIN stock_location loc_from
        ON sm.location_id = loc_from.id
        INNER JOIN stock_location loc_to
        ON sm.location_dest_id = loc_to.id

        LEFT JOIN (
            SELECT
                sqsm.move_id as move_id,
                sum(sq.quantity * sq.cost) as remaining_value,
                sum(sq.quantity) as remaining_qty
            FROM stock_quant_move_rel sqsm
            INNER JOIN stock_quant sq
            ON sqsm.quant_id = sq.id
            INNER JOIN stock_location sl
            ON sq.location_id = sl.id
            WHERE (sl.company_id IS NOT NULL OR sl.usage = 'internal')
            GROUP BY sqsm.move_id
        ) AS q1 ON (q1.move_id = sm.id)

        LEFT JOIN (
            SELECT
                sqsm.move_id as move_id,
                sum(sq.quantity * sq.cost) as value
            FROM stock_quant_move_rel sqsm
            INNER JOIN stock_quant sq
            ON sqsm.quant_id = sq.id
            GROUP BY sqsm.move_id
        ) AS q2 ON (q2.move_id = sm.id)

        WHERE sm.id = to_update.id
        AND (loc_from.company_id IS NULL OR loc_from.usage <> 'internal')
        AND (loc_to.company_id IS NOT NULL OR loc_from.usage = 'internal')
        AND sm.state = 'done'
    """)

    # Valuate outgoing moves:
    # q1: Update value based on quants that a linked to this move.
    env.cr.execute("""
        UPDATE stock_move AS to_update
        SET
            value = -q1.value
        FROM stock_move sm
        INNER JOIN stock_location loc_from
        ON sm.location_id = loc_from.id
        INNER JOIN stock_location loc_to
        ON sm.location_dest_id = loc_to.id

        LEFT JOIN (
            SELECT
                sqsm.move_id as move_id,
                sum(sq.quantity*sq.cost) as value
            FROM stock_quant_move_rel sqsm
            INNER JOIN stock_quant sq
            ON sqsm.quant_id = sq.id
            GROUP BY sqsm.move_id
        ) AS q1 ON (q1.move_id = sm.id)

        WHERE sm.id = to_update.id
        AND (loc_from.company_id IS NOT NULL OR loc_from.usage = 'internal')
        AND (loc_to.company_id IS NULL OR loc_from.usage <> 'internal')
        AND sm.state = 'done'
    """)
```

I don't know enough to say if it would improve performance or actually make it worst...

**Comment by StefanRijnhart** [comment]
@ivantodorovich no problem, please keep those performance improvements coming ;-)

**Pull request merged**
