### PR TITLE
[FIX] let add_fields() work for Odoo <= v8

### PR DESCRIPTION
**Pull request by Yajo**
In those versions, [there is a required column called `select_level`][1] whose [default value is `"0"`][2].

I'm adding it to `add_fields()` so it doesn't crash when trying to use it in those versions.

The crash looks like this:

```
2020-03-12 03:48:38,493 1 ERROR prod openerp.sql_db: bad query:
            INSERT INTO ir_model_fields (
                model_id, model, name, field_description, ttype, state
            ) VALUES (
                117, 'product.template', 'pack', 'OU', 'bool', 'base'
            ) RETURNING id
Traceback (most recent call last):
  File "/opt/odoo/custom/src/odoo/openerp/sql_db.py", line 247, in execute
    res = self._obj.execute(query, params)
IntegrityError: null value in column "select_level" violates not-null constraint
DETAIL:  Failing row contains (9885, product.template, 117, pack, null, null, OU, bool, base, null, f, null, f, null, null, null, null, null, null, null, null, null, null, null, null, null).

2020-03-12 03:48:38,493 1 ERROR prod OpenUpgrade: Error after 0:00:00.000372 running
            INSERT INTO ir_model_fields (
                model_id, model, name, field_description, ttype, state
            ) VALUES (
                117, 'product.template', 'pack', 'OU', 'bool', 'base'
            ) RETURNING id
2020-03-12 03:48:38,493 1 ERROR prod OpenUpgrade: product_pack: error in migration script product_pack/migrations/8.0.1.0.0/pre-migration.py: IntegrityError('null value in column "select_level" violates not-null constraint\nDETAIL:  Failing row contains (9885, product.template, 117, pack, null, null, OU, bool, base, null, f, null, f, null, null, null, null, null, null, null, null, null, null, null, null, null).\n',)
2020-03-12 03:48:38,493 1 ERROR prod OpenUpgrade: null value in column "select_level" violates not-null constraint
```

[1]: https://github.com/odoo/odoo/blob/9e8f70e4849b0eeaca8b5cf51372ecfa23dc561b/openerp/addons/base/ir/ir_model.py#L261
[2]: https://github.com/odoo/odoo/blob/9e8f70e4849b0eeaca8b5cf51372ecfa23dc561b/openerp/addons/base/ir/ir_model.py#L286

@Tecnativa TT22023 TT18838

### CODE REVIEW

**Comment by Yajo** [comment]
But if the column exists as a remnant and it is still required, wouldn't it make sense to check its existence? It would crash anyway without this part.

**Comment by pedrobaeza** [comment]
According latest moves we have done in OpenUpgrade, that constraint should be removed when the column is not in use anymore. I haven't seen any way any problem derived from that column, so it should be done already.

**Comment by Yajo** [comment]
Done.

**Comment by pedrobaeza** [comment]
Sorry for the nitpicking, but you have converted a 5 line log to a very longer log. Please keep the number of lines and also extra empty lines. Take into account that this is logged.

**Comment by Yajo** [comment]
You shouldn't care so much about those meaningless details. :roll_eyes:  Done, anyway.

**Comment by pedrobaeza** [comment]
Yes, I care because I'm the one reading that logs after each migration, and that upsets me, specially in a so low level function.

**Pull request merged**
