### PR TITLE
[IMP] make apidocs available on rtfd.org

### PR DESCRIPTION
**Pull request by blaggacao**
Try to solve the problem, that on ReadTheDocs, still there is no autoupdated docstring apidocumentation available.

Something very useful.

### CODE REVIEW

**Comment by bwrsandman** [comment]
:+1:

**Comment by pedrobaeza** [comment]
:+1:

**Comment by StefanRijnhart** [comment]
Can you point to what it looks like now on RTD?

**Comment by blaggacao** [comment]
I'm actually not sure if this is the right command. It's just an educated guess without knowing how to test it. Does anybody know of somebody to ping who knows how to accomplish this correctly?

**Comment by StefanRijnhart** [comment]
Could you create an account on RTD that is configured to build this branch? Then you can experiment with various settings and build it until it is ready to be adopted by the project.

**Pull request closed without merging**
