### PR TITLE
Publish to PyPI on git tag

### LINKED ISSUE #234: Publish version 3.0 to pypi
https://pypi.org/project/openupgradelib/#history

### PR DESCRIPTION
**Pull request by sbidoul**
This should publish to PyPI when creating a git tag (x.y.z).

closes #234

### CODE REVIEW

**Review by pedrobaeza — APPROVED** [review]
Thanks for this. Let's try if it works.

**Comment by pedrobaeza** [comment]
Working perfectly and very easy to be completed (previously it requires an extra commit with changes in the files, log history, etc)!

https://pypi.org/project/openupgradelib/3.1.0/

Thank you very much, Stéphane.

**Comment by sbidoul** [comment]
Note updating the changelog is not automated ?

**Comment by legalsylvain** [comment]
Hi @agajic-modoolar. Is it fixed by https://github.com/OCA/openupgradelib/pull/244 ?

thanks.

**Pull request merged**
