### PR TITLE
[IMP] rename_models: Handle properties that reference to the old model

### PR DESCRIPTION
**Pull request by pedrobaeza**
Use case: You are renaming from model A to model B, and there are a many2one company dependent (property) field whose relation is model A. The field "value_reference" of these properties are of the form
'A,id'. We have to change them to 'B,id'.

@Tecnativa

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Yeah, right. Both have marginal use, and thus it hasn't made too much noise, but these are rough edges in a "pixel perfect" migration.

**Comment by pedrobaeza** [comment]
You can merge when you want :wink:

**Comment by pedrobaeza** [comment]
Related PR where I have found the problem: https://github.com/OCA/bank-payment/pull/470

**Comment by mreficent** [comment]
Fixed in https://github.com/OCA/openupgradelib/pull/104.

**Pull request merged**
