### PR TITLE
[IMP] .travis.yml: Add auto-deployment. Closes #24

### LINKED ISSUE #24: Enable auto-deployment via Travis
As in https://github.com/OCA/pylint-odoo/pull/2, we can enable auto-deployment to Pypi with Travis, like explained here:

http://docs.travis-ci.com/user/deployment/pypi/

And only activate it when making tags, so we can:

* Remove master and development branch.
* Control the moment when we want to make a release.
* Avoid to have someone with the corresponding credentials.

### PR DESCRIPTION
**Pull request by pedrobaeza**
Only when a tag is applied, the deployment will be done.

### CODE REVIEW

**Comment by StefanRijnhart** [comment]
Sweet! :+1:

**Comment by pedrobaeza** [comment]
Can anyone more review this to merge it?

**Comment by StefanRijnhart** [comment]
Merging this low risk change anyway.

**Comment by pedrobaeza** [comment]
Auto-deployment is not working and I have tried to change user/password (OCA instead oca) to see if that is the problem. @moylop260, can you help with this?

**Comment by moylop260** [comment]
Do you try with `tag -s`?

**Comment by pedrobaeza** [comment]
OK, solved. It was just that the tag doesn't include last commit with the correct password. Thanks anyway.

**Pull request merged**
