### PR TITLE
Revert "[FIX] rename_fields: Don't rename only by name + reverse order"

### PR DESCRIPTION
**Pull request by StefanRijnhart**
Reverts OCA/openupgradelib#207

### CODE REVIEW

**Comment by StefanRijnhart** [comment]
Fasttracking this as it breaks everything.

**Comment by pedrobaeza** [comment]
Why do you revert so quick? The code is correct and it's fixing a problem. I'm investigating the problem in Travis.

**Comment by StefanRijnhart** [comment]
See my comment on the original PR. ie.model_id is not from core Odoo but from base_export_manager. You need to file a new PR that checks if the column exists.

**Comment by pedrobaeza** [comment]
OK, now I see the problem. Why Travis is not offering this information?

**Comment by StefanRijnhart** [comment]
Because nobody writes tests for Openupgradelib even if it is supported? This would have come out today because PRs on Openupgrade would have failed using this version. But because my nightly migration failed today I found out early.

**Comment by pedrobaeza** [comment]
Well, we know the problem here with tests, but the question is not that one. Travis was erroring, but the log was cut, so no clue on what's going on.

**Pull request merged**
