### PR TITLE
[FIX] _adjust_merged_values_orm: get target_record_id value first

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
This way we avoid calling getattr().

### CODE REVIEW

**Comment by pedrobaeza** [comment]
AFAIK, `getattr` was for avoiding incorrect or half-loaded fields that can happen on migration, so it's still needed.

**Comment by MiquelRForgeFlow** [comment]
Ah, ok, I don't really get it, but I believe in you. Then should I close this PR?

**Comment by pedrobaeza** [comment]
Well, there's a part that I like: put first the target record id, but I don't remember why I didn't do it that way, and if first not null exists already as operation and is not taking target record first.

**Review by pedrobaeza — APPROVED** [review]
It makes sense for first not null operation to get the target value first

**Pull request merged**
