### PR TITLE
[FIX] wrong operator

### PR DESCRIPTION
**Pull request by Yajo**
@Tecnativa TT23136

This should fix https://github.com/OCA/OpenUpgrade/pull/2299/checks?check_run_id=1740902592 from https://github.com/OCA/OpenUpgrade/pull/2299

### CODE REVIEW

**Review by MiquelRForgeFlow — APPROVED** [review]

**Review by pedrobaeza — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Fast-tracking this:

/ocabot merge nobump

**Comment by Yajo** [comment]
I hope the bots don't conflict.

**Comment by pedrobaeza** [comment]
I'm deleting one branch for being sure.

**Comment by MiquelRForgeFlow** [comment]
Oh no, I wanted to see what would happen haha

**Pull request merged**
