### PR TITLE
[FIX] Avoid deprecated openerp warning in >= 13.0

### PR DESCRIPTION
**Pull request by mreficent**
Cause: https://github.com/odoo/odoo/commit/7c47eb185443af08a55b0045c6a78f74151dc083.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Why changing the order? This is very fast and only happens once, so no need to change this.

**Comment by mreficent** [comment]
Well, then in v13 and above you will several always warnings.

**Comment by pedrobaeza** [comment]
Which warning?

**Comment by mreficent** [comment]
just try in local v13 of openupgrade and you will see.

**Comment by pedrobaeza** [comment]
Put here that warning, please. And why in previous versions is not failing?

**Comment by mreficent** [comment]
```yml
WARNING ? odoo.modules.module: openerp is a deprecated alias to odoo. Please consider using the latter as the former is going to be removed in the next version. 
DeprecationWarning
```

**Comment by pedrobaeza** [comment]
And switching this, we will get any other warning in previous versions?

**Comment by mreficent** [comment]
No, I think not. Old versions, as I know, they didn't have a warning for calling odoo instead of openerp. If they are very old and doesn't get the odoo call, then the import error will work and will call the openerp.

**Comment by pedrobaeza** [comment]
OK, let's go for it then.

**Pull request merged**
