### PR TITLE
[FIX] savepoint must raise

### PR DESCRIPTION
**Pull request by Yajo**
This is how it works in modern Odoo versions.

@Tecnativa TT18838

### CODE REVIEW

**Comment by pedrobaeza** [comment]
This is not used since ages, and I'm pretty sure it was on purpose to not re-raise... any possible insight about this, @hbrunn @StefanRijnhart ?

**Comment by Yajo** [comment]
Without raising, there's no way to know if the process succeeded or not, as the exception is "eaten" by the context manager.

A few lines above, it reuses `cr.savepoint()` for modern odoo versions that include that method, and [Odoo implementation has been re-raising since v8, where it was introduced](https://github.com/odoo/odoo/blob/9e8f70e4849b0eeaca8b5cf51372ecfa23dc561b/openerp/sql_db.py#L412).

**Comment by hbrunn** [comment]
I don't remember details, but this very much looks like an oversight from my side

**Comment by pedrobaeza** [comment]
OK then, let's merge it.

**Pull request merged**
