### PR TITLE
[IMP] update_module_names: Add merge option

### PR DESCRIPTION
**Pull request by pedrobaeza**
With these minimal changes, we allow to reallocate all the resources related to a module that has been merged into others in later versions. For example, email_template in version 8 that has been integrated in mail module in version 9.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
cc @Tecnativa

**Comment by pedrobaeza** [comment]
Travis error unrelated

**Comment by pedrobaeza** [comment]
@moylop260, do you have any tip why this fails?

**Comment by moylop260** [comment]
Maybe is a flake8-3.2.1 error
```bash
flake8 OCA/openupgradelib
Traceback (most recent call last):
  File "flake8", line 11, in <module>
    sys.exit(main())
  File "flake8/main/cli.py", line 16, in main
    app.run(argv)
  File "flake8/main/application.py", line 322, in run
    self._run(argv)
  File "flake8/main/application.py", line 306, in _run
    self.run_checks()
  File "flake8/main/application.py", line 243, in run_checks
    self.file_checker_manager.start(files)
  File "/flake8/checker.py", line 371, in start
    self.make_checkers(paths)
  File "/flake8/checker.py", line 285, in make_checkers
    if argument == filename or should_create_file_checker(filename)
  File "/flake8/checker.py", line 412, in __init__
    self.display_name = self.processor.filename
AttributeError: 'NoneType' object has no attribute 'filename'
```

**Comment by moylop260** [comment]
It could be related with https://gitlab.com/pycqa/flake8/issues/272

**Comment by pedrobaeza** [comment]
It seems so. Thanks for the info. Is in our hands to repair it?

**Comment by moylop260** [comment]
Options
1. Wait the next releases
2. Freeze a old stable version in pip install command

**Comment by pedrobaeza** [comment]
OK, I think we should choose option 2, isn't it? We did the same on MQT if I don't remember bad.

**Comment by moylop260** [comment]
This project is not using MQT
Use directly flake8 command from .travis.yml

**Comment by pedrobaeza** [comment]
Yeah, I know, that's why I tell to do the same.

**Comment by moylop260** [comment]
We have freeze pylint version from pylint-odoo but [flake8 is not freeze](https://github.com/OCA/maintainer-quality-tools/blob/406b428c97b3/travis/travis_install_nightly#L6)

**Comment by moylop260** [comment]
FYI using 
`flake8 --version`
`2.4.1 (pep8: 1.7.0, mccabe: 0.5.2, pyflakes: 0.8.1) CPython 2.7.10 on Darwin`

`flake8 openupgradelib/`
the result was:
```bash
openupgradelib/openupgrade_tools.py:31:1: E302 expected 2 blank lines, found 1
openupgradelib/openupgrade.py:101:5: F811 redefinition of unused 'RegistryManager' from line 58
```

**Comment by hbrunn** [comment]
what do you think about having a new function to merge module A into B instead? This way, we can account for situations where multiple modules are replaced by another one, and the execution path will be a lot less complicated

**Comment by pedrobaeza** [comment]
I preferred to use the method name for not duplicating code. You can still perform to merge multiple modules into one module:
```
update_module_names([('B', 'A'), ('C', 'A',), ('D', 'A')], merge_modules=True)
```

**Comment by pedrobaeza** [comment]
This is finally working as I have fixed Travis.

@hbrunn @Yajo @cubells, can any of you please check?

**Comment by pedrobaeza** [comment]
As we have already tested this feature and need it for a lot of current PRs, I concede myself the luxury of merging it.

**Pull request merged**
