### PR TITLE
[FIX] add_xmlid: 14.0 compatibility

### PR DESCRIPTION
**Pull request by hildickethan**
When trying to use the `add_xmlid` function in a 14.0 repo it returned the following error:

Traceback error:
```
  File "/opt/odoo/src/repo/addons/x_module/hooks.py", line 17, in pre_init_hook
    openupgrade.add_xmlid(
  File "/opt/odoo/data/.cache/pypi/openupgradelib/openupgrade.py", line 985, in add_xmlid
    logged_query(
  File "/opt/odoo/data/.cache/pypi/openupgradelib/openupgrade.py", line 1310, in logged_query
    cr.execute(query, args)
  File "<decorator-gen-3>", line 2, in execute
  File "/opt/odoo/src/odoo/odoo/sql_db.py", line 101, in check
    return f(self, *args, **kwargs)
  File "/opt/odoo/src/odoo/odoo/sql_db.py", line 298, in execute
    res = self._obj.execute(query, params)
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/odoo/src/odoo/odoo/http.py", line 639, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/src/odoo/odoo/http.py", line 315, in _handle_exception
    raise exception.with_traceback(None) from new_cause
psycopg2.errors.UndefinedColumn: column "date_init" of relation "ir_model_data" does not exist
LINE 1: ... (create_uid, create_date, write_uid, write_date, date_init,...
```

SQL error:
```
odoo.sql_db: bad query: INSERT INTO ir_model_data (create_uid, create_date, write_uid, write_date, date_init, date_update, noupdate, name, module, model, res_id) VALUES (1, (now() at time zone 'UTC'), 1, (now() at time zone 'UTC'), (now() at time zone 'UTC'), (now() at time zone 'UTC'), true, 'category_x', 'x_module', 'product.category', 8)
ERROR: column "date_init" of relation "ir_model_data" does not exist
LINE 1: ... (create_uid, create_date, write_uid, write_date, date_init,...
```

It seems like this is caused, as stated by the error, by the lack of `date_init` and `date_update` existing as fields in `ir.model.data` in 14.0. Removed in this commit https://github.com/odoo/odoo/commit/148f3dabc91fbb59ae5abe6396ca614a708577b9.

My workaround is simply using a different SQL without these fields in the case of an Odoo version of 14.0 or higher and that worked fine for my use/test cases. If anyone has a deeper understanding of these models and can give some insight that would be appreciated!

I have tested this openupgradelib change in 14.0 and 13.0 and it worked as intended.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Thanks for the patch. For the sake of code clarity, it would be good to have a base query string and args, and only on version < 14, add the rest of query and args. Can you please do it?

**Comment by hildickethan** [comment]
> Thanks for the patch. For the sake of code clarity, it would be good to have a base query string and args, and only on version < 14, add the rest of query and args. Can you please do it?

@pedrobaeza Updated! I re-tested on 13.0 and 14.0 and it adds the fields correctly in the lower version, let me know if there is a simpler solution as I may have overcomplicated it a bit

**Review by pedrobaeza — APPROVED** [review]

**Review by StefanRijnhart — APPROVED** [review]
Thanks!

**Pull request merged**
